name: ugz_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+2

environment:
  sdk: ^3.7.0

dependencies:
  app_settings: ^5.1.1
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  device_imei:
    git:
      url: https://github.com/jasonhcgt/device_imei.git
      ref: main
  device_info_plus: ^11.1.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  disable_battery_optimization:
    git:
      url: https://github.com/adeeteya/Disable-Battery-Optimizations.git
      ref: master
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  dropdown_search: ^6.0.2
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_blue_plus: ^1.35.3
  flutter_device_imei: ^0.0.3
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  go_router: ^14.2.7
  google_maps_flutter: ^2.9.0
  http_parser: ^4.1.2
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  in_app_update: ^4.2.3
  infinite_scroll_pagination: ^5.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mime: ^2.0.0
  nfc_manager:
    git:
      url: https://github.com/okadan/flutter-nfc-manager.git
  package_info_plus: ^8.0.2
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.5.2
  signature: ^6.0.0
  skeletonizer: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.10.0
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  go_router_builder: ^2.7.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  drift_dev: ^2.23.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/map/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100

flutter_gen:
  output: lib/src/constants/gen/
  integrations:
    flutter_svg: true
