name: ugz_app
description: "A new Flutter project."
publish_to: "none"

# Internal Test
#version: 0.1.8+18

# Production
version: 1.0.0+24

environment:
  sdk: ^3.7.0

dependencies:
  app_settings: ^5.1.1
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  device_imei:
    git:
      url: https://github.com/jasonhcgt/device_imei.git
      ref: main
  device_info_plus: ^11.4.0
  dio: ^5.7.0
  dio_cache_interceptor: ^4.0.3
  http_cache_hive_store: ^5.0.1
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  dropdown_search: ^6.0.2
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_device_imei: ^0.0.4
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  go_router: ^15.1.1
  google_maps_flutter: ^2.12.1
  http_parser: ^4.1.2
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  in_app_update: ^4.2.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mime: ^2.0.0
  nfc_manager:
    git:
      url: https://github.com/okadan/flutter-nfc-manager.git
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.4.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  signature: ^6.0.0
  skeletonizer: ^1.4.3
  url_launcher: ^6.3.1
  upgrader: ^11.3.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  go_router_builder: ^2.9.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  drift_dev: ^2.26.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/map/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100

flutter_gen:
  output: lib/src/constants/gen/
  integrations:
    flutter_svg: true
